### ISSUE TITLE
Copied and edited from https://github.com/deniscolak/smart-admin-dashboard

### ISSUE THREAD

**Issue by deniscolak** [Eng-Mouaz-M-AlShahmeh/admin_dashboard_flutter_template#1]

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Yes, but I add arabic language and change the design to light mode ...

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
And delete the state of provider which is not working

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
and change every twins animations or any proper design to arabic layout. Thanks 💙😌

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
and change every texts to arabic language..

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
and move every code to the latest version of flutter not just dart 2.12 but to 2.18.5

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
and remove every json packages and files not needed

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
remove every none necessary containers and switched to sized boxes

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
remove every unnecessary print lines

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
add const every where

**Comment by deniscolak** [comment]
Thank you for copying and translating, if you need help please let us know!

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
I do not see in your account over than 8 repos and avatar of apple, but if you want I delete this repo from my account, you are welcome.

**Comment by deniscolak** [comment]
I don't know if you are aware of it, but you are using 2 of those 8 repos in your translation project.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Which of them!

**Comment by deniscolak** [comment]
A pub.dev package -> colorize-text-avatar
An initial repo -> flutter-admin-dasbboard-login
Your translation project -> smart-admin-dashboard

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Translation is better than throwing false accusations on Google Dev Library author

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Yes I updated flutter-admin-dasbboard-login from repo based on dart 2.12 to 2.18.5 and make many changes on it according to rtl layout and Arabic design. and add localization codes to the repo with changing the night mode to light mode.

**Comment by deniscolak** [comment]
👍

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Maybe we need thank @imaNNeoFighT for [fl_chart](https://pub.dev/packages/fl_chart) and @aleksanderwozniak for [table_calendar](https://pub.dev/packages/table_calendar) and @OpenFlutter for [flutter_screenutil](https://pub.dev/packages/flutter_screenutil) and @Milad-Akarie for [smooth_page_indicator](https://pub.dev/packages/smooth_page_indicator) and @deniscolak for [colorize_text_avatar](https://pub.dev/packages/colorize_text_avatar) and me for flutter_localizations. You are welcome 🇸🇾💙😌

**Comment by deniscolak** [comment]
> Translation is better than throwing false accusations on Google Dev Library author

Doesn’t matter Google Dev Library author or certified aws expert, i will always tell the truth

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks.
